### PR TITLE
Revisions and minor restructure.

### PR DESCRIPTION
**Pull request by dmdouglas**
I might have sorted out the structure of our description of communication networks: I've moved the paragraph on the trade-off between reach and targeting to the middle of the description of newspapers. I don't think it pre-empts part of our later description like it did before.

### CODE REVIEW

**Comment by dmdouglas** [comment]
OK, I'm pretty happy with it now. I've tried to connect Act 3 a bit more with Act 1. I also think the conclusion needs a better summary of what you wrote in Act 1. Other than that, all we need is your final revisions, and I think we're good to go!

**Comment by davekinkead** [comment]
On them now ...

**Comment by davekinkead** [comment]
Wow, taking some time here …..

Anyway, I’ve reorganised part 2 a bit more now.  I’m up to utopian internet.

A few points for you to check ….

1. Is it more punchy now? I’ve tried to introduce one point at a time in historical context.
2. I’ve changed the terms uni/bidirectional to simplex/duplex which I think captures it better (and later multiplex for the internet). The issue isn’t just direction of information flow, it is how many messages can be sent at once.

Thoughts?

Hopefully this will be wrapped up in a few hours.

Dave

**Comment by dmdouglas** [comment]
Changes look good to me (still going through them). Simplex/Duplex change is fine. I'm tempted to remove the formal definition of communication (source,receiver,medium,context): it's not doing the work I originally included it for.

**Comment by dmdouglas** [comment]
Act 2 is great! The historical account flows much better and the epistemic factors are much clearer.

**Pull request merged**
